# Generated by Django 2.1.3 on 2018-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_is', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(choices=[('оператор', 'OP'), ('менеджер', 'MR')], default='оператор', max_length=15),
        ),
    ]
